### ISSUE TITLE
messing around in administrator code

### ISSUE THREAD

**Issue by phartleitner** [SusoGym/SEST#2]
I never planned to have the admin verify via email, just the parents!
Two days of work based on the old administrator's code might now be hard to fit into all the changes Smephite has applied. 
:(

**Comment by Smephite** [comment]
Just crate a new branch and I will merge it.

**Comment by Smephite** [comment]
![7ee18657201b90e2cf274252c49de08e](https://cloud.githubusercontent.com/assets/2955065/20370001/8c2c89d6-ac5c-11e6-8ad6-b8e6df0539fa.png)
![312455b5b527b9c3b4080133567b4d27](https://cloud.githubusercontent.com/assets/2955065/20370004/8dbc9dc2-ac5c-11e6-95c3-000f12bbcfee.png)
![d1654c9a4deb4cd3e0f37b287a794aef](https://cloud.githubusercontent.com/assets/2955065/20370006/8f05f0b6-ac5c-11e6-8ccb-976a6de4104b.png)
